version: '3.8'

services:
  # Service Backend
  backend:
    build:
      context: ./backend-mediatheque
      target: ${NODE_ENV:-development}
    container_name: mediatheque-backend
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${BACKEND_PORT:-5001}
      FRONTEND_URL: ${FRONTEND_URL}
    ports:
      - "${BACKEND_PORT:-5001}:5001"
    # Pas de dépendance MongoDB - utilise Atlas directement
    networks:
      - mediatheque-network
    volumes:
      - ./backend-mediatheque/logs:/app/logs
      - ./backend-mediatheque/.env:/app/.env:ro

  # Service Frontend
  frontend:
    build:
      context: ./frontend-mediatheque
      target: ${NODE_ENV:-development}
    container_name: mediatheque-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      VITE_API_URL: ${VITE_API_URL}
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    depends_on:
      - backend
    networks:
      - mediatheque-network
    volumes:
      - ./frontend-mediatheque/src:/app/src:ro
      - ./frontend-mediatheque/.env:/app/.env:ro

# Pas de volumes MongoDB - utilise Atlas

networks:
  mediatheque-network:
    driver: bridge
